dist: trusty
sudo: false

addons:
  apt:
    packages:
    - texlive

before_script: >
  git config --global user.name "Travis CI";
  git config --global user.email "deploy@travis-ci.org";
  git remote add origin https://${GITHUB_TOKEN}@github.com/bjk17/bjk.is.git >/dev/null 2>&1;

script: >
  pdflatex cv.tex && pdflatex cv.tex;
  sed -e 's/^%~ //' cv.tex > cv-full.tex;
  pdflatex cv-full.tex && pdflatex cv-full.tex;

after_script: >
  git add cv.pdf cv-full.pdf;
  git commit --message "Travis build: $TRAVIS_BUILD_NUMBER";
  git push --quiet --set-upstream origin master;

notifications:
  email: false
